package com.example.ssjb.util;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.RectF;
import android.graphics.pdf.PdfDocument;

import com.example.ssjb.data.AttendanceSession;
import com.example.ssjb.data.SessionStudentRow;
import com.example.ssjb.data.Student;
import com.example.ssjb.data.StudentAttendanceStat;

import java.io.File;
import java.io.FileOutputStream;
import java.util.List;
import java.util.Locale;

public final class PdfGenerator {
    private static final int PAGE_WIDTH_LANDSCAPE = 842;
    private static final int PAGE_HEIGHT_LANDSCAPE = 595;
    private static final int PAGE_WIDTH_PORTRAIT = 595;
    private static final int PAGE_HEIGHT_PORTRAIT = 842;
    private static final int MARGIN = 24;

    private PdfGenerator() {
    }

    public static File generate(Context context, AttendanceSession session, List<SessionStudentRow> rows) throws Exception {
        File out = new File(context.getCacheDir(), "attendance_" + session.id + ".pdf");
        PdfDocument document = new PdfDocument();
        try {
            PdfDocument.PageInfo pageInfo = new PdfDocument.PageInfo.Builder(PAGE_WIDTH_LANDSCAPE, PAGE_HEIGHT_LANDSCAPE, 1).create();
            PdfDocument.Page page = document.startPage(pageInfo);
            Canvas canvas = page.getCanvas();

            Paint titlePaint = paint(22, true, Color.rgb(31, 75, 153));
            Paint textPaint = paint(11, false, Color.rgb(30, 36, 48));
            Paint smallPaint = paint(9, false, Color.rgb(90, 98, 112));
            Paint linePaint = paint(1, false, Color.rgb(210, 218, 228));
            linePaint.setStyle(Paint.Style.STROKE);
            Paint fillPaint = paint(0, false, Color.rgb(245, 247, 251));
            fillPaint.setStyle(Paint.Style.FILL);

            int x = MARGIN;
            int y = MARGIN;
            drawTitle(canvas, titlePaint, "CLASS".equals(session.sessionType) ? "Attendance Summary" : "Call Attendance Summary", x, y);
            y += 34;
            canvas.drawText("Generated by SSJB", x, y, smallPaint);
            y += 18;

            int metaTop = y + 8;
            int metaHeight = 72;
            drawRoundedBox(canvas, fillPaint, linePaint, x, metaTop, PAGE_WIDTH_LANDSCAPE - (MARGIN * 2), metaHeight);
            int left = x + 12;
            int top = metaTop + 20;
            canvas.drawText("Type:", left, top, smallPaint);
            canvas.drawText("CLASS".equals(session.sessionType) ? "Class" : "Call", left + 78, top, textPaint);
            canvas.drawText("Date:", left + 220, top, smallPaint);
            canvas.drawText(DateUtils.formatDisplayDate(session.dateIso) + " (" + safe(session.dayLabel) + ")", left + 278, top, textPaint);
            canvas.drawText("Time:", left + 470, top, smallPaint);
            canvas.drawText(safe(session.timeLabel), left + 526, top, textPaint);
            canvas.drawText("Details:", left, top + 24, smallPaint);
            drawWrappedText(canvas, textPaint, buildSessionDetail(session), left + 78, top + 24, PAGE_WIDTH_LANDSCAPE - MARGIN * 2 - 90, 14);

            int present = 0;
            for (SessionStudentRow row : rows) {
                if (row.present) {
                    present++;
                }
            }

            int summaryTop = metaTop + metaHeight + 14;
            int summaryBoxWidth = (PAGE_WIDTH_LANDSCAPE - (MARGIN * 2) - 18) / 4;
            String[] summaryLabels = {"Members", "Present", "Absent", "Attendance"};
            String[] summaryValues = {
                    String.valueOf(rows.size()),
                    String.valueOf(present),
                    String.valueOf(rows.size() - present),
                    String.format(Locale.US, "%.1f%%", rows.isEmpty() ? 0 : (present * 100f / rows.size()))
            };
            for (int i = 0; i < 4; i++) {
                int boxLeft = x + (i * (summaryBoxWidth + 6));
                drawRoundedBox(canvas, fillPaint, linePaint, boxLeft, summaryTop, summaryBoxWidth, 56);
                canvas.drawText(summaryLabels[i], boxLeft + 10, summaryTop + 18, smallPaint);
                canvas.drawText(summaryValues[i], boxLeft + 10, summaryTop + 39, textPaint);
            }

            int rosterTop = summaryTop + 72;
            canvas.drawText("Attendance List", x, rosterTop - 4, textPaint);
            drawRoster(canvas, textPaint, smallPaint, linePaint, null, rows, x, rosterTop, PAGE_WIDTH_LANDSCAPE - (MARGIN * 2), PAGE_HEIGHT_LANDSCAPE - rosterTop - MARGIN);

            document.finishPage(page);
            try (FileOutputStream fos = new FileOutputStream(out)) {
                document.writeTo(fos);
            }
            return out;
        } finally {
            document.close();
        }
    }

    public static File generateStudentSummary(Context context, Student student, StudentAttendanceStat stat) throws Exception {
        File out = new File(context.getCacheDir(), "student_" + student.id + ".pdf");
        PdfDocument document = new PdfDocument();
        try {
            PdfDocument.PageInfo pageInfo = new PdfDocument.PageInfo.Builder(PAGE_WIDTH_PORTRAIT, PAGE_HEIGHT_PORTRAIT, 1).create();
            PdfDocument.Page page = document.startPage(pageInfo);
            Canvas canvas = page.getCanvas();

            Paint titlePaint = paint(22, true, Color.rgb(31, 75, 153));
            Paint textPaint = paint(11, false, Color.rgb(30, 36, 48));
            Paint smallPaint = paint(9, false, Color.rgb(90, 98, 112));
            Paint linePaint = paint(1, false, Color.rgb(210, 218, 228));
            linePaint.setStyle(Paint.Style.STROKE);
            Paint fillPaint = paint(0, false, Color.rgb(245, 247, 251));
            fillPaint.setStyle(Paint.Style.FILL);

            int x = MARGIN;
            int y = MARGIN;
            drawTitle(canvas, titlePaint, "Student Profile", x, y);
            y += 34;
            canvas.drawText("Clean summary for sharing", x, y, smallPaint);
            y += 18;

            int profileHeight = 340;
            drawRoundedBox(canvas, fillPaint, linePaint, x, y + 8, PAGE_WIDTH_PORTRAIT - (MARGIN * 2), profileHeight);
            int rowX = x + 12;
            int rowY = y + 30;
            int rowGap = 26;

            drawLabelValue(canvas, smallPaint, textPaint, "Name", joinName(student), rowX, rowY);
            drawLabelValue(canvas, smallPaint, textPaint, "Middle name", safe(student.middleName), rowX, rowY += rowGap);
            drawLabelValue(canvas, smallPaint, textPaint, "Surname", safe(student.surname), rowX, rowY += rowGap);
            drawLabelValue(canvas, smallPaint, textPaint, "Phone", safe(student.phoneNumber), rowX, rowY += rowGap);
            drawLabelValue(canvas, smallPaint, textPaint, "Instrument", safe(student.instrument), rowX, rowY += rowGap);
            drawLabelValue(canvas, smallPaint, textPaint, "Address", safe(student.address), rowX, rowY += rowGap);
            drawLabelValue(canvas, smallPaint, textPaint, "Joining date", DateUtils.formatDisplayDate(student.joiningDateIso), rowX, rowY += rowGap);
            drawLabelValue(canvas, smallPaint, textPaint, "Knowledge", safe(student.knowledgeLevel), rowX, rowY += rowGap);
            drawLabelValue(canvas, smallPaint, textPaint, "Last updated", DateUtils.formatDisplayDateTime(student.lastUpdatedIso), rowX, rowY += rowGap);
            drawLabelValue(canvas, smallPaint, textPaint, "Balance", student.balance == null ? "-" : String.format(Locale.US, "%.2f", student.balance), rowX, rowY += rowGap);

            int total = stat == null ? 0 : stat.totalSessions;
            int present = stat == null ? 0 : stat.presentCount;
            double percent = total == 0 ? 0 : (present * 100.0 / total);

            int summaryTop = y + profileHeight + 24;
            int summaryBoxWidth = (PAGE_WIDTH_PORTRAIT - (MARGIN * 2) - 6) / 2;
            drawRoundedBox(canvas, fillPaint, linePaint, x, summaryTop, summaryBoxWidth, 74);
            drawRoundedBox(canvas, fillPaint, linePaint, x + summaryBoxWidth + 6, summaryTop, summaryBoxWidth, 74);
            canvas.drawText("Attendance", x + 10, summaryTop + 18, smallPaint);
            canvas.drawText(String.format(Locale.US, "%.1f%%", percent), x + 10, summaryTop + 42, textPaint);
            canvas.drawText("Sessions", x + summaryBoxWidth + 16, summaryTop + 18, smallPaint);
            canvas.drawText(String.valueOf(total), x + summaryBoxWidth + 16, summaryTop + 42, textPaint);

            int extraTop = summaryTop + 92;
            drawRoundedBox(canvas, fillPaint, linePaint, x, extraTop, PAGE_WIDTH_PORTRAIT - (MARGIN * 2), 70);
            canvas.drawText("Present", x + 12, extraTop + 20, smallPaint);
            canvas.drawText(String.valueOf(present), x + 12, extraTop + 43, textPaint);
            canvas.drawText("Status", x + 110, extraTop + 20, smallPaint);
            canvas.drawText(total == 0 ? "No attendance yet" : "Active", x + 110, extraTop + 43, textPaint);

            canvas.drawText("Student attendance details generated by SSJB", x, PAGE_HEIGHT_PORTRAIT - MARGIN, smallPaint);

            document.finishPage(page);
            try (FileOutputStream fos = new FileOutputStream(out)) {
                document.writeTo(fos);
            }
            return out;
        } finally {
            document.close();
        }
    }

    private static void drawRoster(Canvas canvas, Paint textPaint, Paint smallPaint, Paint linePaint, Paint fillPaint, List<SessionStudentRow> rows, int x, int y, int width, int maxHeight) {
        int columns = 3;
        int columnWidth = (width - 16) / columns;
        int rowHeight = 18;
        int rowCount = (int) Math.ceil(rows.size() / 3.0);
        int boxHeight = Math.min(maxHeight, Math.max(48, rowCount * rowHeight + 22));
        drawRoundedBox(canvas, fillPaint, linePaint, x, y, width, boxHeight);

        Paint headerPaint = paint(10, true, Color.rgb(31, 75, 153));
        int headerY = y + 18;
        for (int i = 0; i < columns; i++) {
            int baseX = x + 10 + (i * columnWidth);
            canvas.drawText("Student", baseX, headerY, headerPaint);
            canvas.drawText("Status", baseX + columnWidth - 60, headerY, headerPaint);
        }

        int textY = headerY + 18;
        for (int r = 0; r < rowCount; r++) {
            for (int c = 0; c < columns; c++) {
                int index = (r * columns) + c;
                int baseX = x + 10 + (c * columnWidth);
                if (index < rows.size()) {
                    SessionStudentRow row = rows.get(index);
                    canvas.drawText(truncate(row.name, 24), baseX, textY, textPaint);
                    canvas.drawText(row.present ? "P" : "A", baseX + columnWidth - 54, textY, row.present ? textPaint : smallPaint);
                }
            }
            textY += rowHeight;
            if (textY > y + boxHeight - 12) {
                break;
            }
        }
    }

    private static void drawTitle(Canvas canvas, Paint paint, String title, int x, int y) {
        canvas.drawText(title, x, y + 20, paint);
    }

    private static void drawRoundedBox(Canvas canvas, Paint fillPaint, Paint linePaint, int x, int y, int width, int height) {
        RectF rect = new RectF(x, y, x + width, y + height);
        if (fillPaint != null) {
            canvas.drawRoundRect(rect, 16f, 16f, fillPaint);
        }
        if (linePaint != null) {
            canvas.drawRoundRect(rect, 16f, 16f, linePaint);
        }
    }

    private static void drawLabelValue(Canvas canvas, Paint labelPaint, Paint valuePaint, String label, String value, int x, int y) {
        canvas.drawText(label + ":", x, y, labelPaint);
        drawWrappedText(canvas, valuePaint, value, x + 94, y, PAGE_WIDTH_PORTRAIT - (MARGIN * 2) - 112, 14);
    }

    private static Paint paint(float textSize, boolean bold, int color) {
        Paint paint = new Paint(Paint.ANTI_ALIAS_FLAG);
        paint.setColor(color);
        paint.setTextSize(textSize);
        paint.setFakeBoldText(bold);
        return paint;
    }

    private static void drawWrappedText(Canvas canvas, Paint paint, String text, int x, int y, int width, int lineHeight) {
        String remaining = safe(text);
        int currentY = y;
        while (!remaining.isEmpty()) {
            int count = paint.breakText(remaining, true, width, null);
            if (count <= 0) {
                break;
            }
            String line = remaining.substring(0, count).trim();
            if (line.isEmpty() && remaining.length() > count) {
                remaining = remaining.substring(count).trim();
                continue;
            }
            canvas.drawText(line, x, currentY, paint);
            currentY += lineHeight;
            remaining = remaining.substring(Math.min(count, remaining.length())).trim();
        }
    }

    private static String joinName(Student student) {
        StringBuilder builder = new StringBuilder();
        append(builder, student.name);
        append(builder, student.middleName);
        append(builder, student.surname);
        return builder.length() == 0 ? "-" : builder.toString();
    }

    private static String buildSessionDetail(AttendanceSession session) {
        if ("CLASS".equals(session.sessionType)) {
            return safe(session.classMode);
        }
        StringBuilder builder = new StringBuilder();
        append(builder, session.callTitle);
        append(builder, session.location);
        append(builder, session.callDescription);
        return builder.length() == 0 ? "-" : builder.toString();
    }

    private static void append(StringBuilder builder, String value) {
        if (value == null || value.trim().isEmpty()) {
            return;
        }
        if (builder.length() > 0) {
            builder.append(" | ");
        }
        builder.append(value.trim());
    }

    private static String truncate(String value, int maxChars) {
        String safe = safe(value);
        if (safe.length() <= maxChars) {
            return safe;
        }
        return safe.substring(0, Math.max(0, maxChars - 1)) + "…";
    }

    private static String safe(String value) {
        return value == null || value.trim().isEmpty() ? "-" : value.trim();
    }
}
